### ISSUE TITLE
Set up your Kanban board

### ISSUE THREAD

**Issue by estebanmual** [yersel500/capstone-js#21]
https://github.com/yersel500/capstone-js/projects/1

The team consists of: 

-  @yersel500 
- @estebanmual

**Comment by TedLivist** [comment]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @estebanmual and @yersel500,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted an Issue with a link to your repo, whereas you should have a link to your Kanban board itself

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
